### ISSUE TITLE
Error in example from "quickstart" section

### ISSUE THREAD

**Issue by dragosmacovei** [anrayliu/pyvidplayer2#12]
Traceback (most recent call last):
  File "/home/pi/Desktop/new_video_player.py", line 2, in <module>
    from pyvidplayer2 import Video
  File "/home/pi/.local/lib/python3.7/site-packages/pyvidplayer2/__init__.py", line 22, in <module>
    from .video_player import VideoPlayer
  File "/home/pi/.local/lib/python3.7/site-packages/pyvidplayer2/video_player.py", line 8, in <module>
    class VideoPlayer:
  File "/home/pi/.local/lib/python3.7/site-packages/pyvidplayer2/video_player.py", line 131, in VideoPlayer
    def queue(self, input_: str | Video) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by anrayliu** [comment]
Update your python to the newest version.

**Comment by anrayliu** [comment]
Note for others: As of version 0.9.14, type hints have been removed to allow older python versions to work.
