### ISSUE TITLE
HELP : Error: not a WAVE file

### ISSUE THREAD

**Issue by 2ant** [anrayliu/pyvidplayer2#2]
Hi, i tried to read 3 files on 2 different python versions but i get this : 
`Traceback (most recent call last):
  File "H:\Python\pythonProject\video_player.py", line 43, in <module>
    vid.draw(win, (0, 0), force_draw=False)
  File "C:\Users\antoi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyvidplayer2\video.py", line 227, in draw
    if self._update() or force_draw:
  File "C:\Users\antoi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyvidplayer2\video.py", line 147, in _update
    self._audio.load(self._chunks.pop(0))
  File "C:\Users\antoi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyvidplayer2\audio_handler.py", line 36, in load
    self.wave = wave.open(BytesIO(bytes), "rb")
  File "C:\Users\antoi\AppData\Local\Programs\Python\Python310\lib\wave.py", line 509, in open
    return Wave_read(f)
  File "C:\Users\antoi\AppData\Local\Programs\Python\Python310\lib\wave.py", line 163, in __init__
    self.initfp(f)
  File "C:\Users\antoi\AppData\Local\Programs\Python\Python310\lib\wave.py", line 132, in initfp
    raise Error('not a WAVE file')
wave.Error: not a WAVE file`

**Comment by ree1261** [comment]
Hi there,

Can you please provide me with the files that gave you this error?

**Comment by ree1261** [comment]
I was also unable to replicate your error. Regardless, it's good that you got it working again. For now, I'll leave this issue open. Let me know if the issue pops up again.

**Comment by ree1261** [comment]
Hello, it appears this isn't a problem anymore, so I will be closing this issue. Feel free to open another one if needed.
